project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"
  preview:
    port: 1357
    browser: true

website:
  title: "통계 패키지"
  image: images/koRea_logo.png
  page-navigation: true
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "홈"
      - href: intro.qmd
        text: "들어가며"
      - text: "교재"
        menu:
        - text: "디지털 글쓰기-공용"
          href: writing.qmd
        - text: "통계논문-석박사"
          href: thesis.qmd
        - text: "통계교육용-교사용"
          href: teacher.qmd
        - text: "통계패키지-학생용"
          href: student.qmd
      - text: "교육실행"
        menu:
        - href: operation.qmd
          text: "추진 개요"
        - href: workshop.qmd
          text: "교원연수"
      - href: reference.qmd
        text: "관련자료"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

