project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"
  preview:
    port: 1357
    browser: true

lang: kr

website:
  title: "빛에듀(Bit-Edu)"
  image: images/koRea_logo.png
  page-navigation: true
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "홈"
      - text: "교재"
        menu:
        - text: "디지털 글쓰기-공용"
          href: writing.qmd
        - text: "통계논문-석박사"
          href: thesis.qmd
        - text: "통계교육용-교사용"
          href: teacher.qmd
        - text: "통계패키지-학생용"
          href: student.qmd
        - text: "---"
        - text: "초중등 통계(학생)"
          href: http://aispiration.com/ds-authoring/ds-world-student.html
        - text: "초중등 통계(학부모)"
          href: http://aispiration.com/ds-authoring/data-science-world.html
        - text: "데이터 시각화"
          href: https://aispiration.com/viz/viz.html
        - text: "---"
        - text: "컴퓨터과학 언플러그드"
          href: https://r2bit.com/book_unplugged/
        - text: "리보그"
          href: https://aispiration.com/reeborg/
        - text: "데이터과학 프로그래밍"
          href: https://r2bit.com/book_programming/
        - text: "설치형 통계 패키지(Rcmdr)"
          href: https://r2bit.com/Rcmdr/
        - text: "데이터과학 기본기"
          href: https://r2bit.com/book_analytics/
        - text: "데이터 시각화"
          href: https://r2bit.com/book_viz/
      - text: "교육실행"
        menu:
        - href: operation.qmd
          text: "추진 개요"
        - href: workshop.qmd
          text: "교원연수"
        - text: "---"
        - href: gaise.qmd
          text: "GAISE II (미국)"
        - href: sat/math_2022.qmd
          text: "수능 확률통계"
      - text: "도구"
        menu:
        - href: http://bit2edu.ddns.net/
          text: "빛에듀(Bit-Edu)"
        - text: "---"
        - href: http://bit2edu.ddns.net/docs/digitalwriting/
          text: "디지털 글쓰기"
        - href: https://bitstat.shinyapps.io/bitstat/
          text: "BitStat 통계패키지"
        - href: https://r2bit.shinyapps.io/infer_shiny/
          text: "가설검정"
        - text: "---"
        - href: http://bit2server.ddns.net/app/tidyblocks/ko/
          text: "그래프 tidyblock"
        - href: http://bit2server.ddns.net/app/reeborg/
          text: "리보그(Reeborg)"
      - text: "데이터"
        menu:
        - href: https://r2bit.com/bitData/
          text: "교육용 데이터셋"
        - href: https://r2bit.com/hsData/
          text: "실용통계 교과서 데이터셋"
      - href: reference.qmd
        text: "관련자료"
  sidebar:
    style: docked
    contents:
      - section: "디지털 전자책"
        contents:
        - href: https://r2bit.com/bitBook/
          text: "디지털 글쓰기"
        - href: https://github.com/bit2r/bitBook
          text: "`bitBook` 소스코드"
        - href: https://www.meetup.com/seoul-r-meetup/events/289596122/
          text: "글쓰기 컨퍼런스"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

