project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"
  preview:
    port: 1357
    browser: true

website:
  title: "통계 패키지"
  image: images/koRea_logo.png
  page-navigation: true
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: "수학교육"
        menu:
        - text: "들어가며"
          href: intro.qmd
      - href: reference.qmd
        text: "관련자료"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

