project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"
  preview:
    port: 1357
    browser: true

website:
  title: "통계 패키지"
  image: images/koRea_logo.png
  page-navigation: true
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "홈"
      - href: intro.qmd
        text: "들어가며"
      - text: "교재"
        menu:
        - text: "디지털 글쓰기-공용"
          href: writing.qmd
        - text: "통계논문-석박사"
          href: thesis.qmd
        - text: "통계교육용-교사용"
          href: teacher.qmd
        - text: "통계패키지-학생용"
          href: student.qmd
        - text: "---"
        - text: "초중등 통계(학생)"
          href: http://aispiration.com/ds-authoring/ds-world-student.html
        - text: "초중등 통계(학부모)"
          href: http://aispiration.com/ds-authoring/data-science-world.html
        - text: "데이터 시각화"
          href: https://aispiration.com/viz/viz.html
      - text: "교육실행"
        menu:
        - href: operation.qmd
          text: "추진 개요"
        - href: workshop.qmd
          text: "교원연수"
      - text: "소프트웨어"
        menu:
        - href: http://r2bit.ddns.net/
          text: "디지털 글쓰기"
        - href: https://bitstat.shinyapps.io/bitstat/
          text: "BitStat 통계패키지"
        - href: https://r2bit.shinyapps.io/infer_shiny/
          text: "가설검정"
        - text: "---"
        - href: http://bit2server.ddns.net/shiny/tidyblocks/ko/index.html
          text: "그래프 tidyblock"
      - href: sat/math_2022.qmd
        text: "수능문제"
      - href: reference.qmd
        text: "관련자료"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

