---
title: "통계 논문"
description: 디지털 글쓰기의 첫 걸음을 함께 해봅니다.
date: today # 날짜 설정: now, last-modified
author:
  - name: 이광춘
    url: https://www.linkedin.com/in/kwangchunlee/
    affiliation: 한국 R 사용자회
    affiliation-url: https://github.com/bit2r
title-block-banner: true
#title-block-banner: "#562457"
format:
  html:
    theme: 
      - flatly
      - css/quarto-fonts.css
    code-fold: false
    toc: true
    toc-depth: 2
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
link-citations: yes
editor_options: 
  chunk_output_type: console
---


## 통계 검정

논문작성의 가장 핵심적인 사항은 기본 이론적 배경을 바탕으로 유의미한 새로운 주장 즉, 가설을 제시하고 가설이 사실로 증명될 경우 갖는 의미가 새로운 기여를 한다는 것이 아주 높은 고도에서 바라본 논문의 대략적인 개요가 될 것이다.

이 지점에서 제시한 가설을 증명하는 방법에 여러가지 갈레가 있을 것이며 그 중 데이터를 바탕으로 가설이 맞다는 것을 증명하는 방식을 취하게 된다. 

귀무가설($H_0$)은 흔히 회의적인 시각 혹은 검정해야 되는 주장을 나타낸다. 대립가설 ($H_A$)은 고려중인 대립 주장을 나타내고, 흔히 가능한 모수 값의 범위로 나타낸다. 귀무가설은 흔히 회의적인 자세 혹은 차이 없음 관점을 나타낸다. 대립가설은 흔히 변화가 있다는 가능성처럼 새로운 관점을 나타낸다.

:::{.callout-note}

**가설 검정 얼개(hypothesis testing framework)**

대립가설($H_A$)을 옹호하는 증거가 강력해서 $H_A$ 지지에 대해 ($H_0$)를 거절하지 않는다면, 회의론자는 귀무가설($H_0$)를 기각하지 않을 것이다.

가설검정얼개(hypothesis testing framework)는 매우 일반적인 도구로, 
재고도 않고 흔히 사용된다. 만약 어떤 사람이 다소 믿을 수 없는 주장을 한다면, 처음에는 회의적인 시각을 갖는다. 하지만, 주장을 뒷받침하는 충분한 증거가 있다면, 회의적인 시각을 파기하고 대립가설을 지지하고 귀무가설을 기각한다. 가설검정 전형적인 특징을 미국 사법체제에서도 발견할 수 있다.

미국 법원은 피고에 대한 두가지 가능한 주장을 고려한다: 유죄이거나 무죄다. 가설검정얼개로 주장을 준비한다면, 귀무가설과 대립가설은 각각 어느 것이 될까요? 
[배심원은 증거가 너무나 설득력 있어서 (강해서) 피고가 유죄라는 것에 관해서 합리적 의혹(reasonable doubt)이 없는지를 고려한다; 그런 경우에, 배심원은 결백(귀무가설)을 기각하고, 피고가 유죄(대립가설)라고 판결한다.]{.aside}

:::


가설검정 방식은 Frequentist와 Bayesian으로 과거 나눠졌으나 최근에는 "코딩을 통한 통계가설검정" 이 기계학습, 인공지능의 부상으로 미국 학부에서 많이 다뤄지고 있다. Frequestist 가설검정 방법론이 대세가 된 것은 RA Fisher (붓꽃 데이터 저자) 명성과 계산량이 상대적으로 다른 방법론에 비해 적어 다수 통계 패키지에 탑재되면서 보편적인 가설검정방법으로 받아들여지게 되었다. 

[Frequentist 가설검정은 NHST(Null Hypothesis Significance Testing) 으로 알려져 있으며 NHST 5 단계에 대한 자세한 사항은 [NEDARC, Hypothesis Testing](https://www.nedarc.org/statisticalhelp/advancedstatisticaltopics/hypothesisTesting.html)을 참조한다. ]{.aside}


컴퓨터를 이용하여 수학적 사전 지식이 적게 필요하고 직관적인 이해를 통해 가설검정을 수행한다는 점에서 최근에 "코딩을 통한 통계가설검정"이 부상하고 있다.

- Allen Downey, [http://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html](http://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html)
- [http://aispiration.com/statistics/stat-inference.html](http://aispiration.com/statistics/stat-inference.html)
- tidymodels - infer : [https://infer.tidymodels.org/](https://infer.tidymodels.org/)
    
## 가설검정 방법

1. 귀무가설 설정
1. 대립가설 설정
1. 유의수준 설정
1. 검정통계량과 P-값 도출
1. 결론

## 소프트웨어

- [오픈 가설검정 소프트웨어](https://r2bit.shinyapps.io/infer_shiny/)

## 통계 소프트웨어

- [BitSlide](https://r2bit.com/bitSlide/)
- [통계 국산화](http://aispiration.com/data-science/ds-korean-stat-pkg.html)
- [로우코드 Shiny 앱 개발](https://r2bit.com/bitSlide/slideshow/202211-meetup/#/title-slide)



