---
title: "대학수학능력시험 문제"
subtitle: "확률과 통계"
editor: source
---

# 2022학년도

## 23번 문제

23. 다항식 $(x+2)^7$ 전개식에서 $x^5$의 계수는? \[2점\]

① 42\
② 56\
③ 70\
**④ 84**\
⑤ 98

$$
{}_7 C_5 \times x^5 \times 2^2 \\~\\
{}_7 C_2 \times 2^2 \times x^5= \frac{7\times 6}{2} \times 4 = 42 \times 2 = 84
$$

## 24번 문제

24. 확률변수 $X$ 가 이항분포 $B(n,\frac{1}{3})$을 따르고 $V(2X) =40$ 일 때, $n$의 값은? \[3점\]

① 30 ② 35 ③ 40 **④ 45** ⑤ 50

1.  $V(2X) = 4V(X) = 40$ 따라서, $V(X) = 10$

2.  $V(X) = n \times p \times (1-p) = n \times \frac{1}{3} \times \frac{2}{3} = n \times \frac{2}{9}=10$ 따라서, $n=45$

## 3번 문제

3.  1 부터 10까지 자연수가 하나씩 적혀 있는 10 장의 카드가 들어 있는 주머니가 있다. 이 주머니에서 임의로 카드 3 장을 동시에 꺼낼 때, 꺼낸 카드에 적혀 있는 세 자연수 중에서 가장 작은 수가 4 이하이거나 7 이상일 확률은? \[3점\]

① $\frac{4}{5}$ ② $\frac{5}{6}$ **③** $\frac{13}{15}$ ④ $\frac{9}{10}$ ⑤ $\frac{14}{15}$

## 27번 문제

27. 어느 자동차 회사에서 생산하는 전기 자동차의 1회 충전 주행 거리는 평균이 $m$이고 표준편차가 $\sigma$인 정규분포를 따른다고 한다. 이 자동차 회사에서 생산한 전기 자동차 100 대를 임의추출하여 얻은 1회 충전 주행 거리의 표본평균이 $\bar{x}_1$ 일 때, 모평균 $m$에 대한 신뢰도 95 %의 신뢰구간이 $a \le m \le b$ 이다. 이 자동차 회사에서 생산한 전기 자동차 400대를 임의추출하여 얻은 1회 충전 주행 거리의 표본평균이 $\bar{x}_2$일 때, 모평균 $m$에 대한 신뢰도 95%의 신뢰구간이 $c \le m \le d$이다. $\bar{x}_1 - \bar{x}_2 = 1.34$이고 $a=c$ 일 때, $b-a$의 값은? (단, 주행 거리의 단위는 km이고, $Z$가 표준정규분포를 따르는 확률변수일 때 $P(|Z|\le1.96)=0.95, P(|Z|\le 2.58)=0.99$ 로 계산한다.) \[3점\]

① 5.88 **② 7.84** ③ 9.80 ④ 11.76 ⑤ 13.72

$$ \bar{x}\_1 - 1.96 \frac{\sigma}{\sqrt{100}} \le m \le \bar{x}\_1 + 1.96 \frac{\sigma}{\sqrt{100}} \\~\\

\bar{x}\_1 - 1.96 \frac{\sigma}{10} \le m \le \bar{x}\_1 + 1.96 \frac{\sigma}{10} \\~\\$$

$$ \bar{x}\_2 - 2.58 \frac{\sigma}{\sqrt{400}} \le m \le \bar{x}\_2 + 2.58 \frac{\sigma}{\sqrt{400}} \\~\\

\bar{x}\_2 - 2.58 \frac{\sigma}{20} \le m \le \bar{x}\_2 + 2.58 \frac{\sigma}{20}$$

상기 식에서 $a,c$는 다음과 같이 정의된다.

$$
\bar{x}_1 - 1.96 \frac{\sigma}{10} \rightarrow a \\~\\
\bar{x}_2 - 2.58 \frac{\sigma}{20} \rightarrow c
$$

그리고 $a=c$이 성립하기 때문에

\$\$ \bar{x}\_1 - 1.96 \frac{\sigma}{10} = \bar{x}\_2 - 2.58 \frac{\sigma}{20} \\\~\\

\bar{x}\_1 - \bar{x}\_2 = 1.96 \frac{\sigma}{10} - 2.58 \frac{\sigma}{20} \$\$ 여기서 $\bar{x}_1 - \bar{x}_2 = 1.34$로 주어졌기 때문에 $\sigma$를 구할 수 있다.

$$
1.34 =  1.96 \frac{\sigma}{10}  - 2.58 \frac{\sigma}{20} = \\~\\
 \frac{\sigma}{20}(3.92-2.58) = \frac{\sigma}{20}\times1.34
$$ 따라서, $\sigma = 20$

$$
b-a = 2 \times 1.96 \times \frac{20}{10} = 4 \times 1.96 = 7.84
$$

# 2021학년도 가형(홀수)

[[2021학년도 대학수학능력시험 수학가형 전문항 해설](https://www.youtube.com/watch?v=L9fFwHIqIW0)]{.aside}

## 6번 문제

6.  정규분포 $N(20, 5^2)$을 따르는 모집단에서 크기가 16인 표본을 임의추출하여 구한 표본평균을 $\bar{X}$라 할 때, $E(\bar{X}) + \sigma(\bar{X} )$의 값은? \[3점\]

① $\frac{83}{4}$ **②** $\frac{85}{4}$ ③ $\frac{87}{4}$ ④ $\frac{89}{4}$ ⑤ $\frac{91}{4}$

표본평균은 모평균과 같다.

$$
E(\bar{X}) = 20
$$ 표본 분산은 모표준편차를 표본으로 나눠줘야 구할 수 있다. 즉,

$$
\sigma(\bar{X}) = \frac{5}{\sqrt{16}} = \frac{5}{4}
$$

따라서,

$$
E(\bar{X}) + \sigma(\bar{X} ) = 20 + \frac{5}{4} = \frac{85}{4}
$$
## 22번 문제

22. \$\big( x + \frac{3}{x^2} \big)\^5 \$ 의 전개식에서 $x^2$의 계수를 구하시오. \[3점\]

$${}_5 C _4 \times x^4 \times \big( \frac{3}{x^2} \big)^1 \\~\\
{}_5 C _1 \times x^2 \times 3 = 5 \times 3 \times x^2 = 15 \times x^2
$$

12. 확률변수 $X$는 평균이 8, 표준편차가 3 인 정규분포를 따르고, 확률변수 $Y$ 는 평균이 $m$, 표준편차가 $\sigma$인 정규분포를 따른다. 두 확률변수 $X, Y$가 \$P(4 \le X \le 8) + P(Y\ge 8)=\frac{1}{2} \$ 을 만족시킬 때, $P(Y \le 8 + \frac{2\sigma}{3}$의 값을 오른쪽 표준정규분포표를 이용하여 구한 것은? \[3점\]

① 0.8351 ② 0.8413 ③ 0.9332 **④ 0.9772** ⑤ 0.9938

| $z$ | $P(0\le Z \le z )$   |
|------|--------|
| 1.0  | 0.3413 |
| 1.5  | 0.4332 |
| 2.0  | 0.4772 |
| 2.5  | 0.4938 |



